spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://findinn.crs668a662e8.ap-northeast-2.rds.amazonaws.com:3306/FindInn?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: "!findinn"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true